spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.30.155.5:3306/teachoa?characterEncoding=utf8
    username: root
    password: 123456
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  thymeleaf:
    mode: LEGACYHTML5
mybatis:
  type-aliases-package: com.qf.pojo
pagehelper:
  helper-dialect: mysql